### ISSUE TITLE
Error in drillHole.m

### ISSUE THREAD

**Issue by Enable72** [hongzimao/image_inpainting#1]
When I am running the imagePreprocessing.m function, it says error in drillHole.m line 5, 
Index in position 1 is invalid. Array indices must be positive integers or logical values.

Error in drillHole (line 5)
        newMask(x+i, y) = 0;

Error in imagePreprocessing/Draw (line 28)
            mask = drillHole(mask, y, x);
 
Error while evaluating Figure WindowButtonMotionFcn.

Index in position 1 is invalid. Array indices must be positive integers or logical values.

**Comment by hongzimao** [comment]
Just found you closed the issue. Would be nice if you can also write down how you resolve it? I think this was from one of my undergraduate course projects and I honestly lost track of what I did..

**Comment by Enable72** [comment]
Hi
Actually I was getting the error when my pointer went out of the image
region while masking. I guess when the cursor remains inside the image
there is no error but there would be a issue when the region to be
inpainted lies on the boundary.
